[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

// netlify/functions/hello-world.js
exports.handler = async function(event, context) {
  return {
    statusCode: 200,
    body: "Hello, World!",
  };
};